id: I8948F78F
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 14:37:08.368415+00:00
last_modified: 2022-12-14 14:37:08.368422+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-26T04:14:37.687Z'
  creationid: celso
  eft-text-id: UT22084-090-007
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_563-Upholding_the_Great_Secret_Mantra-v1
bases:
  '6915':
    source_metadata: null
    order: 1
    base_file: 6915.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
